asset_types = {
    "4k": "401K and Other Non-Federal Retirement Accounts",
    "5c": "529 College Savings Plan",
    "5p": "529 Prepaid Tuition Plan",
    "ab": "Asset-Backed Securities",
    "ba": "Bank Accounts, Money Market Accounts and CDs",
    "co": "Collectibles",
    "cs": "Corporate Securities (Bonds and Notes)",
    "db": "Defined Benefit Pension",
    "do": "Debts Owed to the Filer",
    "ds": "Delaware Statutory Trust",
    "ef": "Exchange Traded Funds (ETF)",
    "eq": "Excepted/Qualified Blind Trust",
    "et": "Exchange Traded Notes",
    "fa": "Farms",
    "fe": "Foreign Exchange Position (Currency)",
    "fn": "Fixed Annuity",
    "fu": "Futures",
    "gs": "Government Securities and Agency Debt",
    "he": "Hedge Funds & Private Equity Funds (EIF)",
    "hn": "Hedge Funds & Private Equity Funds (non-EIF)",
    "ic": "Investment Club",
    "ih": "IRA (Held in Cash)",
    "ip": "Intellectual Property & Royalties",
    "ir": "IRA",
    "mf": "Mutual Funds",
    "oi": "Ownership Interest (Holding Investments)",
    "ol": "Ownership Interest (Engaged in a Trade or Business)",
    "op": "Options",
    "ot": "Other",
    "pe": "Pensions",
    "ps": "Stock (Not Publicly Traded)",
    "re": "Real Estate Invest. Trust (REIT)",
    "rp": "Real Property",
    "sa": "Stock Appreciation Right",
    "st": "Stocks (including ADRs)",
    "tr": "Trust",
    "va": "Variable Annuity",
    "vi": "Variable Insurance",
    "wu": "Whole/Universal Insurance",
}
